name: Build and release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build app
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: yarn run make

      - name: Release app
        # If the commit is tagged with a version (e.g. "v1.0.0"),
        # release the app after building
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
